---
- name: Automatización Nodo Network Core (Nativo)
  hosts: localhost
  become: yes
  tasks:
    - name: FASE 1 - Instalar dependencias
      apt:
        name: [kea-dhcp4-server, unbound]
        state: present
        update_cache: yes

    - name: FASE 2 - Crear directorios y escribir configuraciones automáticamente
      copy:
        dest: "{{ item.path }}"
        content: "{{ item.content }}"
        mode: '0644'
      with_items:
        - path: /etc/kea/kea-dhcp4.conf
          content: |
            {
              "Dhcp4": {
                "interfaces-config": { "interfaces": [ "eth0" ] },
                "subnet4": [
                  {
                    "subnet": "192.168.1.0/24",
                    "pools": [ { "pool": "192.168.1.50-192.168.1.150" } ]
                  }
                ],
                "valid-lifetime": 4000
              }
            }
        - path: /etc/unbound/unbound.conf
          content: |
            server:
                interface: 0.0.0.0
                access-control: 192.168.1.0/24 allow
                do-ip4: yes
                do-udp: yes
                do-tcp: yes
                verbosity: 1

    - name: FASE 3 - Reiniciar y habilitar servicios
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - kea-dhcp4-server
        - unbound
